mathan lecture 1 lol
WoWaster/lecture-notes pull request #10
Opened 2022-09-27 20:05 UTC by oveeernight

С оглавлением еще не разбирался, + надо будет еще одну небольшую выкладку добавить, скоро будет

2022-09-28 17:36 UTC, WoWaster requested changes
У меня 2 основных замечания:
1. Написано суховато, хотелось бы больше пояснений, но это задача со звездочкой, потому что Широков тоже очень _много_ говорит
2. На счет ссылок на формулы, может быть проще будет использовать стандратный метод с `\label` `\eqref`, но это лишь мои мысли, если тебе удобнее делать как есть сейчас -- пожалуйста, главное, чтобы нумерация не уезжала от формулы. Это задача с двумя звездочками

2022-09-28 17:36 UTC, WoWaster commented on bachelor-2/semester-3/mathan/lecture1.tex
> +    $ \forall x_1, x_2 \in \mathbb{R}^m, \forall p, q \in \mathbb{R}^n \Rightarrow$
```suggestion
    $ \forall x_1, x_2 \in \mathbb{R}^m, \forall p, q \in \mathbb{R}^n \implies$
```
По сути одно и то же (ну почти, тут стрелка длиннее), а читать потом это код проще

2022-09-28 17:36 UTC, WoWaster commented on bachelor-2/semester-3/mathan/lecture1.tex
> +    $A(px_1 qx_2) = pA(x_1) + qA(x_2)$
```suggestion
    \[A(px_1 qx_2) = pA(x_1) + qA(x_2)\]
```
Эту штучку бы хорошо в выключную формулу

2022-09-28 17:36 UTC, WoWaster commented on bachelor-2/semester-3/mathan/lecture1.tex
> +    $A \leftrightarrow \tilde{A}_{m \times n}$
```suggestion
    $A \Leftrightarrow \tilde{A}_{m \times n}$
```
Наверное все-таки равносильность

2022-09-28 17:36 UTC, WoWaster commented on bachelor-2/semester-3/mathan/lecture1.tex
> +    \end{pmatrix}$
Эта штука лучше бы смотрелась в каком-нибудь `gather*`

2022-09-28 17:36 UTC, WoWaster commented on bachelor-2/semester-3/mathan/lecture1.tex
> +     {||AX||_{\mathbb{R}^n}}$
Выключная формула наверное смотрелась бы лучше

2022-09-28 17:36 UTC, WoWaster commented on bachelor-2/semester-3/mathan/lecture1.tex
> +\end{displaymath}
`\[ \]` или `equation*` (что одно и тоже) всяко лучше `displaymath` [link](https://tex.stackexchange.com/questions/5788/is-there-a-difference-between-the-displaymath-and-equation-environments)

2022-09-28 17:36 UTC, WoWaster commented on bachelor-2/semester-3/mathan/lecture1.tex
> +$$
1. Использовать `$$` в LaTeX грубо говоря вообще запрещено [link](https://tex.stackexchange.com/questions/503/why-is-preferable-to)
2. Вместо такой сложной конструкции можно просто использовать окружение `gather*`, а для длинных многострочных выкладок `multline*`

2022-09-28 17:36 UTC, WoWaster commented on bachelor-2/semester-3/mathan/lecture1.tex
> +     {||AX||_{\mathbb{R}^n}}$
И еще, если бесит `\stackrel{def}{=}`, используй `\equiv`

2022-09-28 17:36 UTC, WoWaster commented on bachelor-2/semester-3/mathan/lecture1.tex
> +\end{enumerate}
Если это теоремы, то зачем снаружи `enumerate`? TeX сам всё пронумерует, а условия можно внести в тело теоремы, ей от этого хуже не станет

2022-09-28 17:36 UTC, WoWaster commented on bachelor-2/semester-3/mathan/lecture1.tex
> +        $$
Здесь весь текст вместе с формулами можно написать в строку и с `$ $`

2022-09-28 17:36 UTC, WoWaster commented on bachelor-2/semester-3/mathan/lecture1.tex
> +    \end{proof}
Это какой-то монстр. Чекни эту [статью](https://www.overleaf.com/learn/latex/Aligning_equations_with_amsmath) и сделай красиво, пожалуйста

2022-09-28 17:36 UTC, WoWaster commented on bachelor-2/semester-3/mathan/lecture1.tex
> +% !TeX root = ./main.tex
Не очень понятно завел ли ты latexindent, если нет, то очень советую)

2022-09-28 17:36 UTC, WoWaster commented on bachelor-2/semester-3/mathan/lecture1.tex
> +    $A: \mathbb{R}^m \rightarrow \mathbb{R}^n$ -- линейный оператор, если
```suggestion
    $A: \R^m \rightarrow \R^n$ -- линейный оператор, если
```
Советую почитать преамбулу, там несколько команд для упрощения жизни уже определены. Если тебе нужны специфичные для матана штуки, пиши их в `main.tex`

2022-10-02 11:11 UTC, oveeernight commented on bachelor-2/semester-3/mathan/lecture1.tex
> +    \end{proof}
разбавил бесконечные $$ $$ алигнами и гэзерами, должно быть посиматичнее. но все равно их много, потому что нумерованных формул десятки

2022-10-02 12:44 UTC, oveeernight commented on bachelor-2/semester-3/mathan/lecture1.tex
> +    $A \leftrightarrow \tilde{A}_{m \times n}$
в рукописном конспекте вроде <-->

2022-10-02 12:46 UTC, oveeernight commented
Добавил 5 лекцию, поправил замечания. Которые вряд ли надо перепроверять пометил resolved. 2-4 появятся попозже. В 5 лекции постарался выкладки разбавлять словами Широкова, но не уверен, что это никого с толку не собьёт

2022-10-08 17:17 UTC, WoWaster requested changes
Очень хочется, чтобы ты пофиксил `\eqno` на `\tag` и избавился от кучи `\[\]` ради красивого вертикального расстояния и читаемости кода, и подумай над окружением для больших доказательств, надо оно или нет

2022-10-08 17:17 UTC, WoWaster commented on bachelor-2/semester-3/mathan/partial_derivatives.tex
> +        \begin{proof}
Если учесть какие ужасные отступы в комбинации рамка + нумерация получились, то может быть для матана можно отключить рамку или сделать еще один вид proof без рамки и соответсвенно без отступов для больших доказательств

2022-10-08 17:17 UTC, WoWaster commented on bachelor-2/semester-3/mathan/linear_operator_norm.tex
> +        \[F(x_0+H) - Y_0 = \lambda \eqno\mathrm{(22^\prime)} \]
```suggestion
          \begin{gather*}
        \Phi(Y_0 + \lambda) - \Phi(Y_0) = B \lambda + \rho(\lambda) \tag{17} \\
        B = D\Phi(Y_0), \rho(\lambda) \in {\vR}^k \text{ и } \frac{||\rho(\lambda)||_{{\vR}^k}}{||\lambda||_{{\vR}^n}} \xrightarrow[\lambda \to \mathbb{0}_n]{}0 \tag{18} \\
        \lambda = \mathbb{0}_n, \Phi(Y_0) - \Phi(Y_0) = \mathbb{0}_k + \rho(\mathbb{0}_n) \rightarrow \rho(\mathbb{0}_n) = \mathbb{0}_k \\
        \forall \eta > 0 \exists \delta_1 > 0 : \\
        (18) \implies\forall \lambda \in {\vR}^n, \lambda \neq \mathbb{0}_n \text{ и } ||\lambda||_{{\vR}_n} <\delta_1 \text{ будет } \frac{||\rho(\lambda)||_{{\vR}_k}}{||\lambda||_{{\vR}^n}} < \eta \tag{19}
        \intertext{и}
        ||\rho(\lambda)||_{{\vR}^k} \leq \eta \cdot ||\lambda||_{{\vR}^n}  \tag{20} \\
        (19) \implies ||\rho(\lambda)||_{{\vR}^k} \leq \eta \cdot ||\lambda||_{{\vR}^n} \tag{19'} \\
        \forall \varepsilon > 0 \exists \delta_2 > 0 : \forall H \in {\vR}^m, ||H||_{{\vR}^m} \delta_2  \text{ имеем } \\
        ||r(H)||_{{\vR}^n} \leq \varepsilon||H||_{{\vR}^m} \tag{21} \\
        H \in {\vR}^m, x_0 + H \in \Omega \text{ возможно т.к. внутрення точка}\\
        F(X_0) = Y_0 \\
        \text{определим } F(x_0 + H) - F(x_0) = \lambda \tag{22} \\
        F(x_0+H) - Y_0 = \lambda \tag{22'}
    \end{gather*}
```
Соу, `\eqno` очень старая штука, возможно еще из первоначального TeX, вместо нее нужно юзать `\tag`, который сильно современнее, а так же прекрасно работает внутри `gather`, так что все отступы вертикальные можно победить
Еще, для стрелочки с подписью есть современная `\xrightarrow[sub]{sup}`, а так же русские варианты греческих букв тоже переопределены как стандартные

2022-10-08 17:17 UTC, WoWaster commented on bachelor-2/semester-3/mathan/partial_derivatives.tex
> +                по  теореме из предыдущей лекции 22.09.22
Теорему лучше зарефернсить через `\label \ref`

2022-10-08 20:09 UTC, oveeernight commented on bachelor-2/semester-3/mathan/partial_derivatives.tex
> +                по  теореме из предыдущей лекции 22.09.22
референс будет, когда появится лекция

2022-10-10 08:46 UTC, WoWaster approved these changes
Ура, вроде все красиво

2022-10-10 08:47 UTC, merged