first lecture
WoWaster/lecture-notes pull request #14
Opened 2023-02-18 17:21 UTC by KubEF

2023-02-18 19:05 UTC, WoWaster requested changes
Для первого творения очень даже круто. :+1:

2023-02-18 19:05 UTC, WoWaster commented on bachelor-2/semester-4/mathematical-logic/01_propositionals_formules.tex
> +\end{document}
У меня нет слов, насколько больно на это смотреть.
Но у меня есть предложения как это сделать лучше:
* возможно не стоит пытаться это уместить в 2 столбца
* или наоборот поиграться с `align` 
* стоит подписать что и как называтся, или написать общий вариант типа `$(* \vdash)$/$(\vdash *)$ -- правило введения $*$ в антецедент/сукцедент`
* покопайся вот [здесь](https://www.logicmatters.net/latex-for-logicians/nd/) и выбери какой-нибудь пакет, чтобы рисовать вывод менее костыльным способом

2023-02-18 19:37 UTC, KubEF commented on bachelor-2/semester-4/mathematical-logic/01_propositionals_formules.tex
> +\end{enumerate}
Здесь не очень понял, почему? До этого без проблем и часто использовалось такое обозначение

2023-02-18 19:38 UTC, KubEF commented on bachelor-2/semester-4/mathematical-logic/01_propositionals_formules.tex
> +\begin{definition}[Пропозициональные формулы]
Совсем не понял, какой аргумент?

2023-02-19 06:45 UTC, WoWaster commented on bachelor-2/semester-4/mathematical-logic/01_propositionals_formules.tex
> +\end{enumerate}
Может не очень понятно про что я. Я про вот эту запись: $\\& | \land ; \cdot ; and $. Не очень понятно зачем мы вообще отделяем первый значок от других. Хочется как минимум пояснения про это, что слева значок, который будет дальшее, а остальные просто аналоги. 
Включая совсем формалиста, $\mid$ у нас вообще является символом Шеффера и при чем тут он, может быть лучше заснуть альтернативы в скобки типа $\\&\ (\land;\ \cdot;\ and)$

2023-02-19 06:46 UTC, WoWaster commented on bachelor-2/semester-4/mathematical-logic/01_propositionals_formules.tex
> +\begin{definition}[Пропозициональные формулы]
Упс, и правда отобразилось не очень, я про аргумент у `definition`

2023-02-19 06:48 UTC, WoWaster commented on bachelor-2/semester-4/mathematical-logic/01_propositionals_formules.tex
> +        \end{align*}
В документации к amsmath это раздел 3.6

2023-02-19 07:26 UTC, WoWaster commented on bachelor-2/semester-4/mathematical-logic/01_propositionals_formules.tex
> +\end{document}
Я сам чуточку покопался по ссылке:
* `proof.sty` судя по короткому гайду будет очень неудобен, давно не обновлялся, и, кажется, его нет на ctan
* `prftree` выглядит очень плохо читаемо
* `bussproofs` и `ebproof` очень похожи друг на друга, но есть отличия
  * `bussproofs` обновлялся довольно давно; по-умолчанию центрирует строки, а не выравнивает их по, например штопору; арность указывается словом 
  * `ebproof` сильно моложе; умеет в выравнивание по `&`; арность указывается числом

2023-02-19 10:01 UTC, merged