bimbambum
WoWaster/lecture-notes pull request #7
Opened 2022-09-14 10:44 UTC by chilison

2022-09-14 15:00 UTC, WoWaster commented on bachelor-2/semester-3/algebra-and-number-theory/01_linear_operators_algebra.tex
> +    Любая ситуация, где поле $K \subset R$ ($R$ - кольцо) $\implies R$ - $K$-алгебра. В обратную сторону тоже верно, если алгебра содержит единицу. Тогда там найдется подкольцо, которое можно отожест
```suggestion
    Любая ситуация, где поле $K \subset R$ ($R$ -- кольцо) $\implies R$ -- $K$-алгебра. 
    В обратную сторону тоже верно, если алгебра содержит единицу. Тогда там найдется подкольцо, которое можно отожествить с полем $К$.
```

2022-09-14 15:04 UTC, WoWaster commented on bachelor-2/semester-3/algebra-and-number-theory/01_linear_operators_algebra.tex
> +Тогда отображение $\End \ V \xrightarrow{\lambda_E} M_n(K), \mca \mapsto [\mca]_E$ - изоморфизм алгебр над полем $K$ (т.е. биекция сохраняет все операции)
Все-таки использование `\xrightarrow` ломает меняет междустрочное расстояние, вместо этого можно написать `\lambda_E : \End V \rightarrow M_n(K)`

2022-09-14 15:06 UTC, WoWaster commented on bachelor-2/semester-3/algebra-and-number-theory/01_linear_operators_algebra.tex
> +\end{gather*}
Не уверен, что Жуков сам много про это сказал, но просто так врубится в эту выкладку сложновато

2022-09-14 15:09 UTC, WoWaster commented on bachelor-2/semester-3/algebra-and-number-theory/01_linear_operators_algebra.tex
> +        \item $\Im \ \mca$ - $A$-инвариантен
```suggestion
        \item $\Ker \mca$ - $A$-инвариантно
        \item $\Im \mca$ - $A$-инвариантен
```
Дико смотрится)

2022-09-14 15:13 UTC, WoWaster commented on bachelor-2/semester-3/algebra-and-number-theory/01_linear_operators_algebra.tex
> +$$\mca_2: V/W \rightarrow V/W \quad v+W \mapsto \mca v+W$$
```suggestion
\[\mca_2: V/W \rightarrow V/W \quad v+W \mapsto \mca v+W\]
```

2022-09-14 15:13 UTC, WoWaster commented on bachelor-2/semester-3/algebra-and-number-theory/01_linear_operators_algebra.tex
> +$$W\xrightarrow{\mca} W \quad w\mapsto \mca w$$
```suggestion
\[W\xrightarrow{\mca} W \quad w\mapsto \mca w\]
```

2022-09-14 15:13 UTC, WoWaster commented on bachelor-2/semester-3/algebra-and-number-theory/01_linear_operators_algebra.tex
> +    $$K \xrightarrow{\varphi} A_0 \quad \alpha \mapsto \alpha_1$$
```suggestion
    \[K \xrightarrow{\varphi} A_0 \quad \alpha \mapsto \alpha_1\]
```

2022-09-14 15:16 UTC, WoWaster commented on bachelor-2/semester-3/algebra-and-number-theory/01_linear_operators_algebra.tex
> +\right) = A_2$
```suggestion
    Таким образом, $[\mca_2]_{e_{m+1}+W, \ldots, e_n+W} =
        \begin{pmatrix}
            a_{m+1m+1} & \ldots & a_{m+1n} \\
            \vdots     & \ddots & \vdots   \\
            a_{nm+1}   & \ldots & a_{nn}   \\
        \end{pmatrix}
        = A_2$
```

2022-09-14 15:22 UTC, WoWaster commented on bachelor-2/semester-3/algebra-and-number-theory/01_linear_operators_algebra.tex
> +    $\varphi(1) \neq 0 \Rightarrow Ker(\varphi)\neq K$.
Кстати, преамбула переопределяет `\phi` как `\varphi`, так что `\varphi` можно заменить на `\phi`

2022-09-14 15:22 UTC, WoWaster commented on bachelor-2/semester-3/algebra-and-number-theory/01_linear_operators_algebra.tex
> +$(\End \ V, $+$)$ - абелева группа. Проверка дистрибутивности операторов:
```suggestion
$(\End \ V, +)$ - абелева группа. Проверка дистрибутивности операторов:
```
Cursed

2022-09-14 15:28 UTC, WoWaster commented on bachelor-2/semester-3/algebra-and-number-theory/01_linear_operators_algebra.tex
> +\end{proof}
```suggestion
\begin{proof}
    Проверка линейности:
    \begin{multline*}
        \mca_2((v_1+W)+(v_2+W))= \mca_2((v_1+v_2)+W)=\\
        \mca(v_1+v_2)+W=  \mca v_1+\mca v_2+W=\\
        (\mca v_1+W)+(\mca v_2+W)
    \end{multline*}
    \begin{multline*}
        \mca_2(\alpha(v+w))= \mca_2(\alpha v+W)=\\
        \mca(\alpha v)+W= \alpha \mca v +W=\\
        \alpha(\mca v +W) = \alpha \mca_2(v+W)
    \end{multline*}
\end{proof}
```
Кажется так читается проще

2022-09-14 15:36 UTC, WoWaster commented on bachelor-2/semester-3/algebra-and-number-theory/01_linear_operators_algebra.tex
> +\right)$
```suggestion
$1 \Rightarrow 2$: векторы $e_1, \ldots ,e_n \in W \Rightarrow$
    \[\mca e_1, \ldots ,\mca e_m \in W = \Lin(e_1, \ldots ,e_m) \Rightarrow
        [\mca]_{e_1, \ldots ,e_n} = \left(
        \begin{tabular}{c|c}
                $A_1$ & $B$   \\ \hline
                0     & $A_2$ \\
            \end{tabular}
        \right)\]
```
Фиксит проблему с растяжением строчных формул

2022-09-14 15:37 UTC, WoWaster commented on bachelor-2/semester-3/algebra-and-number-theory/01_linear_operators_algebra.tex
> +        $\Rightarrow \mca e_1,\ldots  ,\mca e_m \in \Lin(e_1,\ldots ,e_m) \in W$
```suggestion
    $2 \Rightarrow 1$:
    \[[\mca_1]_{e_1, \ldots ,e_n} = \left(\begin{array}{c|c}
                A_1 & B   \\ \hline
                0   & A_2 \\
            \end{array}\right)
        \Rightarrow \mca e_1,\ldots  ,\mca e_m \in \Lin(e_1,\ldots ,e_m) \in W\]
```

2022-09-14 15:40 UTC, WoWaster commented on bachelor-2/semester-3/algebra-and-number-theory/01_linear_operators_algebra.tex
> +\chapter{Алгебра линейных операторов}
```suggestion
\chapter{Алгебра линейных операторов} \marginpar{07.09.22}
```
Укажет справа дату лекции, сейчас бесполезно, во время сессии может помочь

2022-09-14 16:19 UTC, chilison commented on bachelor-2/semester-3/algebra-and-number-theory/01_linear_operators_algebra.tex
> +    $\varphi(1) \neq 0 \Rightarrow Ker(\varphi)\neq K$.
got it

2022-09-20 15:33 UTC, WoWaster requested changes
Убери, пожалуйста, из гита все pdfки, кроме main.pdf.

2022-09-20 15:33 UTC, WoWaster commented on bachelor-2/semester-3/algebra-and-number-theory/01_linear_operators_algebra.tex
> +\begin{definition}>
```suggestion
\begin{definition}
```

2022-09-20 15:33 UTC, WoWaster commented on bachelor-2/semester-3/algebra-and-number-theory/01_linear_operators_algebra.tex
> +>>>>>>> 9501109197be8c7a080a2a3db29ca85cdf1bef45
Здесь что-то страшное

2022-09-20 15:33 UTC, WoWaster commented on bachelor-2/semester-3/algebra-and-number-theory/01_linear_operators_algebra.tex
> +            {U_F'} \& {V_F'}
```suggestion
            {U_{E'}} \& {V_{F'}}
```
Штришок должен быть у базисов, а еще у U вроде базис E'

2022-09-20 15:33 UTC, WoWaster commented on bachelor-2/semester-3/algebra-and-number-theory/03__еigenvalues_and_eigenvectors.tex
> +    Если $K$ — числовое поле, то "собственное число = собственное значение".
```suggestion
    Если $K$ — числовое поле, то <<собственное число = собственное значение>>.
```
В России предпочитают елочки вместо лапок

2022-09-20 15:33 UTC, WoWaster commented on bachelor-2/semester-3/algebra-and-number-theory/03__еigenvalues_and_eigenvectors.tex
> +    слагаемые  - противоречие с линейной независимостью.
```suggestion
       \begin{equation}\label{eigenvalues:direct_sum}
        (v_1 - v_1') + \ldots + (v_k - v_k') = 0
    \end{equation}

    Предположим, $\exists i : v_i = v_i'$. Тогда в \eqref{eigenvalues:direct_sum}  есть ненулевое слагаемое:
    $v_i - v_i' \in V_{\lambda_i}$. Оставим в \eqref{eigenvalues:direct_sum} только ненулевые
    слагаемые  - противоречие с линейной независимостью.
```
Если уж очень хочется **, то можно посмотреть [сюда](https://tex.stackexchange.com/a/12029). Но я бы не советовал, потому что в будущем вполне может появится еще одно уравнение ** и все сломается

2022-09-25 13:28 UTC, Ythosa commented
Че коммиты не сквошите

2022-09-26 16:20 UTC, merged